# Generated by Django 3.2 on 2021-05-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippets',
            field=models.CharField(default='Click Link above to read the Blog Posts.. ', max_length=255),
        ),
    ]
