# Generated by Django 3.2 on 2021-05-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_post_snippets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippets',
            field=models.CharField(max_length=255),
        ),
    ]
