# Generated by Django 3.2 on 2021-05-06 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0011_auto_20210506_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter_url',
        ),
    ]
