# Generated by Django 3.2 on 2021-05-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0013_auto_20210506_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
    ]
